### PR TITLE
Initial Changes To New Docs

### PR DESCRIPTION
**Pull request by AndyHydro**
Creating new and improved docs

### CODE REVIEW

**Comment by ikongpogi** [comment]
Good job. This is great..

**Comment by karn90** [comment]
That's nice

**Comment by andreasbp** [comment]
Awesome ..

**Comment by danqujigy** [comment]
Great job. Its mind blowing

**Comment by surejoe** [comment]
Great step.

**Comment by Juwanna-P** [comment]
Great job..

**Comment by ksamotech** [comment]
Great and awesome project...

**Comment by AndyHydro** [comment]
We are moving the docs to a new repo

**Comment by yogeshkampalliwar** [comment]
great

**Comment by rmzbaig05** [comment]
Nice

**Pull request closed without merging**
